"""drop category table

Revision ID: 1473454727c6
Revises: 62b83a09d1b4
Create Date: 2020-01-08 16:48:06.840814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1473454727c6'
down_revision = '62b83a09d1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.add_column('arts', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arts', 'category')
    op.create_table('categories',
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category'], ['arts.no'], name='categories_category_fkey'),
    sa.PrimaryKeyConstraint('no', name='categories_pkey')
    )
    # ### end Alembic commands ###
