"""add column on art table

Revision ID: 80d06607a18a
Revises: b5f8736b5a23
Create Date: 2019-12-26 15:50:05.298892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d06607a18a'
down_revision = 'b5f8736b5a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arts', 'status')
    # ### end Alembic commands ###
