"""create order table

Revision ID: b92b8f44e2a4
Revises: 1473454727c6
Create Date: 2020-02-06 12:27:03.799136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92b8f44e2a4'
down_revision = '1473454727c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('no', sa.String(), nullable=False),
    sa.Column('item_no', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('orderedBy', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['item_no'], ['arts.no'], ),
    sa.ForeignKeyConstraint(['orderedBy'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
